#Travis-ci config file

sudo: required
dist: trusty

services:
  - docker

before_install:
  - docker build -t patrick .
  - wget http://cdn.knrdesign.co/dist/fonts/patrick-mark1-fonts.zip
  - unzip patrick-mark1-fonts.zip -d map_gallery/carto

script:
  - docker run -v `pwd`:/tmp/build --workdir /tmp/build/map_gallery --entrypoint make patrick -B

notifications:
  email:
    recipients:
      - gliese.q@gmail.com
      - kotaimen.c@gmail.com
