#Travis-ci config file

sudo: required
dist: trusty

services:
  - docker

before_install:
  - docker build -t patrick .
  - cd map_gallery/carto; wget http://cdn.knrdesign.co/dist/fonts/patrick-mark1-fonts.zip
  - cd map_gallery/carto; unzip patrick-mark1-fonts.zip

script:
  - mkdir -p map_gallery/carto/res/Stage
  - convert -size 30x256 'gradient:' -rotate 90 -interpolate Bicubic \( +size xc:#334466  xc:grey50 xc:#f7ba9d +append \) -clut map_gallery/carto/res/Stage/tint.png
  - docker run -v `pwd`:/tmp/build --workdir /tmp/build/map_gallery --entrypoint make patrick -B

notifications:
  email:
    recipients:
      - gliese.q@gmail.com
      - kotaimen.c@gmail.com
