#Travis-ci config file

sudo: required
dist: trusty

install:
  - curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
  - sudo apt-get install -yq nodejs imagemagick python-lxml
  - sudo pip install -rrequirements.txt
  - sudo npm install -g carto

script:
  - cd map_gallery && make

notifications:
  email:
    recipients:
      - gliese.q@gmail.com
      - kotaimen.c@gmail.com
