#Travis-ci config file

sudo: required
dist: trusty

language: node_js

install:
  - sudo apt-get install -yq imagemagick python-lxml
  - sudo pip install -rrequirements.txt
  - sudo npm install -g carto

script:
  - cd map_gallery; make

notifications:
  email:
    recipients:
      - gliese.q@gmail.com
      - kotaimen.c@gmail.com
