#Travis-ci config file

sudo: required
dist: trusty

services:
  - docker

before_install:
  - docker-compose build

script:
  - docker-compose run patrick -B

notifications:
  email:
    recipients:
      - gliese.q@gmail.com
      - kotaimen.c@gmail.com
